### PR TITLE
[Security] Fix inventory duplication

### LINKED ISSUE #167: Dup bug
Dup bug

### PR DESCRIPTION
**Pull request by SettingDust**
Terrible XD https://github.com/SpongePowered/SpongeForge/issues/3097

### CODE REVIEW

**Comment by games647** [comment]
Oh.... I invested so much time looking into this. Do you tested if it's fixed now.

**Comment by SettingDust** [comment]
> Oh.... I invested so much time looking into this. Do you tested if it's fixed now?

Publish in my group. 1:37 in China now. So just 1 people test it. I'll get the answer tomorrow

**Comment by SettingDust** [comment]
It's Ok. And sponge has fixed this bug.

**Comment by games647** [comment]
So does your change work below 4005?

**Comment by SettingDust** [comment]
> So does your change work below 4005?

Not only. But not necessarily above 4005

**Comment by SettingDust** [comment]
> So does your change work below 4005?

Not only. But not necessarily after 4005

**Review by TuxCoding — APPROVED** [review]
Okay thanks, I could verify that it's working on both version ranges. I had to check that before merging in order to verify that it's not causing any other side effects on the newer versions.

**Comment by games647** [comment]
I published a security advisory on the ReadMe page. This should get everyone informed. Thanks again for the patch.

**Pull request merged**
